nginx:
  ports:
    - 443:443/tcp
    - 80:80/tcp
  labels:
    io.rancher.sidekicks: nginx-gen, letsencrypt
  tty: true
  image: nginx
  volumes:
    - proxyPasswd:/etc/nginx/htpasswd
    - proxyConf:/etc/nginx/conf.d
    - proxyVhost:/etc/nginx/vhost.d
    - proxyHtml:/usr/share/nginx/html
    - ${base_path}/certs:/etc/nginx/certs:ro
  stdin_open: true

nginx-gen:
  tty: true
  image: jwilder/docker-gen
  volumes:
    - ${base_path}/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
  volumes_from:
    - nginx
  command: "-notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
  stdin_open: true

letsencrypt:
  tty: true
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes:
    - ${base_path}/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx
  environment:
    NGINX_DOCKER_GEN_CONTAINER: nginx-gen
  stdin_open: true
